apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildachart.fullname" . }}
  labels:
    env: dev
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
     env: dev
