apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildachart.fullname" . }}
  labels:
    {{- include "buildachart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: buildachart
    app.kubernetes.io/instance: release-e4102bf387177d27af57c241dafbf2d76ff200e2
    env: dev
